# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main","master","ticket#*" ]
  pull_request:
    branches: [ "main","master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: frontend/package-lock.json
        cache: 'npm'
    - name: run npm ci at frontend
      working-directory: ./frontend
      run: npm ci
    # - name: run npm start at frontend
    #   working-directory: ./frontend
    #   run: npm start
    - name: run npm build at frontend
      working-directory: ./frontend
      run: npm run build --if-present
      env:
         CI: false
    # - name: run npm deploy at frontend
    #   working-directory: ./frontend
    #   run: npm run deploy
    #   env:
    #      CI: false
    # - name: run npm test at frontend
    #   working-directory: ./frontend
    #   run: npm test
